spring:
  datasource:
    url: jdbc:oracle:${DB_HOMOLOG_SERVER:thin:@oracle.fiap.com.br}:${DB_HOMOLOG_PORT:1521}:${DB_HOMOLOG_NAME:ORCL}
    username: ${DB_HOMOLOG_USERNAME:RM550790}
    password: ${DB_HOMOLOG_PASSWORD:210205}
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true